# This is a basic workflow to help you get started with Actions

name: Python script

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
     aaa: ${{ steps.runn.outputs.aaa}}
     bbb: ${{ steps.runn.outputs.bbb}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: runn
        id: runn      
        env:
          AZURE_SECRET_TOKEN: ${{ secrets.AZURE_SECRET_TOKEN }}
        run: | 
        python -c "import sys; print(sys.version) ;print(f'::set-output name=aaa::5')"
        #echo "::set-output name=aaaa::world" 
        python .github/workflows/example.py
      - name: Output filename
        run: |
        echo "${{steps.runn.outputs.aaa}}"
        echo "${{steps.runn.outputs.bbb}}"  
